# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190814_0303'),
        ('accounts', '0003_auto_20190815_0336'),
    ]

    operations = [
    ]
