---
- hosts: all
  vars:
      host: "{{ inventory_hostname }}"

  tasks:
      - name: Run the equivalent of "apt-get update" as a separate step
        apt:
          update_cache: yes
      - name: make sure required packages are installed
        apt:
          pkg: nginx,git,python3,python3-venv
          state: present

      - name: allow long hostanames in nginx
        lineinfile:
          dest: /etc/nginx/nginx.conf
          regexp: '(\s+)#? ?server_name_hash_bucket_size'
          backrefs: yes
          line: '\1server_name_hash_bucket_size 64;'

      - name: add nginx config to site_available
        template:
          src: ./nginx.conf.j2
          dest: /etc/nginx/sites-available/{{ host }}
        notify:
            - restart nginx

      - name: add symlink in nginx sites-enabled
        file:
          src: /etc/nginx/sites-available/{{ host }}
          dest: /etc/nginx/sites-enabled/{{ host }}
          state: link
        notify:
            - restart nginx

      - name: write gunicorn service script
        template:
          src: ./gunicorn.service.j2
          dest: /etc/systemd/system/gunicorn-{{ host }}.service
        notify:
            - restart gunicorn

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart gunicorn
      systemd:
        name: gunicorn-{{ host }}.service
        daemon_reload: yes
        enabled: yes
        state: restarted
